# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShapefileToGen4
                                 A QGIS plugin
 This plugin convert Shapefiles to Gen4 for John Deere.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-29
        copyright            : (C) 2023 by Petr Sirucek
        email                : psirucek@seznam.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShapefileToGen4 class from file ShapefileToGen4.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shapefile_gen4 import ShapefileToGen4
    return ShapefileToGen4(iface)
